print("Welcome to the boday mass index calculator")
height = input("Please enter your height in m: ")
weight = input("Please enter your weight in kg: ")
a = float(height)
b = float(weight)
print(round(b / a**2))